[project]
name = "flask-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
